# Generated by Django 3.1.3 on 2020-12-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_auto_20201205_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemafield',
            old_name='field',
            new_name='value',
        ),
        migrations.AddField(
            model_name='schemafield',
            name='type',
            field=models.CharField(choices=[('NM', 'Name'), ('AG', 'Age'), ('EM', 'Email'), ('PH', 'Phone'), ('RI', 'Range Integer')], default='NM', max_length=2),
        ),
    ]
