# Generated by Django 3.1.3 on 2020-12-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0004_auto_20201205_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemafield',
            name='type',
            field=models.CharField(choices=[('Name', 'Name'), ('Age', 'Age'), ('Email', 'Email'), ('Phone', 'Phone'), ('Integer', 'Range Integer')], default='Name', max_length=7),
        ),
    ]
