# Generated by Django 3.1.3 on 2020-12-05 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0005_auto_20201205_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='field',
        ),
    ]
