# Generated by Django 3.1.3 on 2020-12-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0006_remove_schema_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemafield',
            name='end',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='schemafield',
            name='start',
            field=models.IntegerField(default=1),
        ),
    ]
