# Generated by Django 3.1.3 on 2020-12-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0008_auto_20201207_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemafield',
            name='placeholder',
            field=models.CharField(max_length=5000, null=True, verbose_name='Placeholder'),
        ),
    ]
