# Generated by Django 3.1.3 on 2020-12-07 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0009_schemafield_placeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemafield',
            name='placeholder',
        ),
        migrations.CreateModel(
            name='FieldRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=5000, verbose_name='Data')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_rows', to='schemas.schemafield')),
            ],
        ),
    ]
