# Generated by Django 3.1.3 on 2020-12-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0010_auto_20201207_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemafield',
            name='type',
            field=models.CharField(choices=[('Name', 'Name'), ('Age', 'Age'), ('Email', 'Email'), ('Phone', 'Phone'), ('Range Integer', 'Range Integer')], default='Name', max_length=13),
        ),
    ]
